services:
  vault:
    image: hashicorp/vault:1.14.4
    container_name: vault-dev
    command: 
      - server
    environment:
      - 'VAULT_LOCAL_CONFIG={"storage": {"file": {"path": "/vault/file"}}, "listener": [{"tcp": { "address": "0.0.0.0:8200", "tls_disable": true}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h", "ui": true}'
    cap_add:
      - "IPC_LOCK"
    ports:
      - 8200:8200
  init:
    image: hashicorpvaultutils:latest
    