name: Release
on:
  push:
    branches: [ "main", "next" ]
  workflow_dispatch:
jobs: 
  qa:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
  release:
    runs-on: ubuntu-latest
    needs: qa
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
            python-version: "3.11"
            cache: "poetry"
      - run: poetry install
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
            extra_plugins: |
                @semantic-release/exec
                @semantic-release-plus/docker
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          DOCKER_USERNAME: eirik-talberg
          DOCKER_PASSWORD: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
